config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#destroy'
  
  #insert the contact page later

  # I probably dont need this routes
  get 'organisations/new'
  get 'shifts/new'

  #defining the restful routes for users
  resources :users do
    resources :shifts
  end

  #defining the routes for organisations
  resources :organisations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root "application#hello"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    #executes the code and then renders the view
    #because there is no code, it just renders the view
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="https://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
  <%= link_to "Back", root_path %>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://www.railstutorial.org/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Adnat</h1>
<!-- Testing the login function -->
<% if logged_in? %>
  <p>
    Logged in as: <%= current_user.name %><br>
    <%= link_to "Check your profile page!", current_user %>
  <p>
<% else %>
<p> Welcome to Adnat, please choose one of the options below: </p>
<ul>
  <li><%= link_to "Sign Up", signup_path %></li>
  <li><%= link_to "Log In", login_path %></li>
  <li><%= link_to "Forgot my password", '#' %></li>
  <li><%= link_to "About", about_path %></li>
</ul>

<% end %>