config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#destroy'
  
  #insert the contact page later

  # I probably dont need this routes
  get 'organisations/new'
  get 'shifts/new'

  #defining the restful routes for users
  resources :users do
    resources :shifts
  end

  #defining the routes for organisations
  resources :organisations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root "application#hello"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :shifts
    # note: i had to comment the belongs_to :organisation so whoever is testing the system is 
    # able to create a new user, otherwise rails will not allow to create a user without an organisation
    #belongs_to :organisation
    #just a reminder that ApplicationRecord inherits from ActiveRecord::Base
    #therefore User (and other models) come with a lot of methods that allows us to interact
    #with the database and other stuff

    

    #makes it downcase before saving
    before_save { self.email = email.downcase }

    # there must be a name! (presence: true is a one element options hash). Our names should stay with 50 chars
    validates :name, presence: true, length: {maximum: 50}
    #remember, this is the same as
    #validates(:name, {presence: true})

    #there must be an email
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i #simplified regex email from https://www.railstutorial.org/book/modeling_users
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}

    #a user has a password
    #here i used the method has_secure_password following the instructions of
    #https://www.railstutorial.org/book/modeling_users
    has_secure_password # this uses a hash function called bcrypt, see the gemfile

    #with has_secure_password, we get:
    #The ability to save a securely hashed password_digest attribute to the database
    # A pair of virtual attributes (password and password_confirmation),
    # including presence validations upon object creation and a validation requiring that they match
    # An authenticate method that returns the user when the password is correct (and false otherwise)
    # the user database table needs a password_digest attribute
    
    #password needs validation, adnat requires a minimum length of 6
    validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # executes code and renders the /users/id page
  def show
    @user = User.find(params[:id])
  end
  
  # executes code and renders the sign up page
  def new
    @user = User.new #empty user that will be updated by the form_for in the view
  end

  # handle the creation of the users after submission of the form in the sign up page
  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      # Handle a successful save.
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user #the same as redirect_to user_url(@user)
      # note: here i can redirect to home_page and change the home page according to the user
      # something like: if @user then display the organisations. It might be easier to keep
      # a list of organisations at the home page so we can update the user organisation
    else
      render 'new'
    end
  end

  #remember the order of the restful routes/actions
  #index
  #show
  #edit
  #new
  #create
  #update
  #destroy

  private
    def user_params
      # the user params require a user hash and allows only the name, email, password and password confirmation attributes
      # this is called strong parameters
      # rails does not allow to pass the full params hash
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>

<%= form_for(@user) do |f| %>

    <%= render 'shared/error_messages' %>

    <p><%= f.label :name %><br>
    <%= f.text_field :name %></p>

    <p><%= f.label :email %><br>
    <%= f.email_field :email %></p>

    <p><%= f.label :password, "Password (6 characters minimum)" %><br>
    <%= f.password_field :password %></p>

    <p><%= f.label :password_confirmation, "Confirmation" %><br>
    <%= f.password_field :password_confirmation %></p>

    <p><%= f.submit "Sign up" %></p>
<% end %>

<p> 
    <%= link_to "Log In", login_path %>
</p>

app/views/users/show.html.erb
<%-# TODO: Check if i need to change the title here -%>
<% provide(:title, "User Home") %>
<h1>Adnat</h1>
<p> 
    <%= "Logged in as " + @user.name %>
    
    <%= link_to "Log Out", logout_path, method: :delete %>
</p>


<% organisations = getAllOrganisations %>
<% if !organisations.empty? %>
    <% if !current_user.organisation_id.nil?%>
        <p>List organisations for current_user</p>
    <% else %>
        <p>Currently you do not belong to any organisation. </p>
        <p>Please choose one of the organisations below or <%= link_to "Create and Join an organisation", new_organisation_path %> </p>
        <ul>
        <% @organisations.each do |organisation| %>
              <li><%= organisation.name %>              
              <%= link_to 'Edit', '#' %>
              <%= link_to 'Join', '#' %></li>
        <% end %>
        </ul>
    <% end %>
<% else %>
    <p>There are no organisations in the database!</p>
    <p>Please create and join one</p>
    <p> <%= link_to "Create and Join an organisation", new_organisation_path %>
<% end %>

<p> (Note: view shifts allows the user to view the shifts as required and would be transferred to inside the organisation list) </p>
<p> <%= link_to "View Shifts", user_shifts_path(@user) %>